spring.application.name=Trocabook

spring.mvc.contentnegotiation.favor-path-extension=true
spring.mvc.contentnegotiation.ignore-accept-header=true

spring.resources.cache.period=0685
spring.resources.static-locations=classpath:/static/

google.recaptcha.key.site=${RECAPTCHA_SITE_KEY}
google.recaptcha.key.secret=${RECAPTCHA_SECRET_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD} 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true


# Configura o atributo SameSite para o cookie de sess�o JSESSIONID
# 'Strict' � a op��o mais segura. 'Lax' � uma alternativa menos restritiva.
server.servlet.session.cookie.same-site=Strict

# Define o diret�rio base para o upload de arquivos
file.upload-dir=C:/uploads

firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH}
google.books.api.key=${GOOGLE_BOOKS_API_KEY}